### ISSUE TITLE
flag to ignore SSL certificate errors

### ISSUE THREAD

**Issue by anoordover** [Software-Improvement-Group/sigridci#72]
We execute the script behind the proxy.
This results in a ssl certificate error.
I know that we should be able to solve this in our environment but for testing it is easier to suppress ssl errors using the context in de urllib by setting a command-line flag.

**Comment by MichielCuijpers** [comment]
@anoordover  you solved this now right? so no need to disable https any more ;-)

**Comment by dennis-sig** [comment]
@anoordover After talking to our security team, we feel we cannot offer this option in a responsible way. Offering such a feature sends the wrong signal as we want to help clients to be more secure, especially since HTTPS certificate validation is a rather standard security practice. 

Obviously @MichielCuijpers and the rest of us will continue to work with you to solve this for your environment, but without having a way to bypass Sigrid CI's security measures.

**Comment by anoordover** [comment]
@dennis-sig, @MichielCuijpers If you want I can create a PR where ssl is checked against an included pem file.

**Comment by MichielCuijpers** [comment]
@anoordover thanks for solving the issue you had by including the pem files in your fork https://github.com/anoordover/sigridci
I asked our security team to look into your solution. @dennis-sig

**Comment by MichielCuijpers** [comment]
reopen

**Comment by MichielCuijpers** [comment]
hi @anoordover closing this request

**Comment by sten-rosendahl** [comment]
We encountered a similar problem when running sigridci.py on a Windows machine, it didn't found valid certificates in python 3.9. One solution that works without manually adding a pem file is to use certifi and ssl and replace the standard call:
urllib.request.urlopen(uploadRequest)
with:
urllib.request.urlopen(uploadRequest, context=ssl.create_default_context(cafile=certifi.where()))

**Comment by MichielCuijpers** [comment]
Hi @sten-rosendahl thanks for the suggestion to use certifi, in other situations we noticed that this article helped https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

cc @dennis-sig
